run:
  timeout: 1m
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  go: "1.20"
  skip-dirs:
    - order_service/proto
  skip-files:
    - ".*\\.pb\\.go"

linters:
  disable-all: true

  enable:
    - asasalint
    - asciicheck
    - bidichk
    - contextcheck
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exportloopref
    # - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - predeclared
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars

linters-settings:
  gocritic:
    disabled-checks:
      - commentFormatting

  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported 
        disabled: true

  stylecheck:
    checks: ["all", "-ST1000"]


issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
