CREATE TABLE IF NOT EXISTS accounts (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGSERIAL NOT NULL,
  amount BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS account_orders (
  id BIGSERIAL PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES accounts ON DELETE RESTRICT,
  event_id BIGINT NOT NULL UNIQUE
);
