grpc:
  port: 8001
  max_idle_connection_lifetime: 60s
  max_connection_age: 60s
  timeout: 60s

db:
  max_connections: 30
  max_connection_lifetime: 30s
  max_idle_connection_lifetime: 120s
  connection_retries: 3
  connection_retry_interval: 10s

kafka_consumer:
  broker_urls:
    - kafka:29092
  topic: "orders.public.order_create_events"
  heartbeat_interval: 5s
  handler_timeout: 30s
  worker_count: 8

logger:
  level: DEBUG
